//HintName: PageResolverExtensions.g.cs
using Plugin.Maui.SmartNavigation;
using Microsoft.Maui.Hosting;

// ---------------
// <auto-generated>
//   Generated by the SmartNavigation Auto-registration module.
//   https://github.com/matt-goldman/Plugin.Maui.SmartNavigation
// </auto-generated>
// ---------------

namespace TestAssembly;

public static class PageResolverExtensions
{

    public static MauiAppBuilder UseAutodependencies(this MauiAppBuilder builder)
    {
         var ViewModelMappings = new Dictionary<Type, Type>();

         // pages
         builder.Services.AddTransient<global::TestAssembly.HomePage>();
         builder.Services.AddTransient<global::TestAssembly.Test1Page>();
         builder.Services.AddTransient<global::TestAssembly.Test2Page>();
         builder.Services.AddTransient<global::TestAssembly.Test3Page>();


         // ViewModels
         builder.Services.AddTransient<global::TestAssembly.HomePageViewModel>();
         builder.Services.AddSingleton<global::TestAssembly.Test2ViewModel>();
         builder.Services.AddTransient<global::TestAssembly.Test3ViewModel>();


         // Services
         builder.Services.AddSingleton<global::TestAssembly.MyService>();
         builder.Services.AddSingleton<global::TestAssembly.IMy2Service, global::TestAssembly.My2Service>();
         builder.Services.AddSingleton<global::TestAssembly.ISingletonService, global::TestAssembly.SingletonService>();
         builder.Services.AddSingleton<global::TestAssembly.Singleton2Service>();
         builder.Services.AddTransient<global::TestAssembly.ITransientService, global::TestAssembly.TransientService>();
         builder.Services.AddTransient<global::TestAssembly.Transient2Service>();


         // ViewModel to Page mappings
         ViewModelMappings.Add(typeof(global::TestAssembly.HomePage), typeof(global::TestAssembly.HomePageViewModel));
         ViewModelMappings.Add(typeof(global::TestAssembly.Test2Page), typeof(global::TestAssembly.Test2ViewModel));
         ViewModelMappings.Add(typeof(global::TestAssembly.Test3Page), typeof(global::TestAssembly.Test3ViewModel));


         // Initialisation
         builder.Services.UseSmartNavigation(ViewModelMappings);
         return builder;
    }
}