//HintName: PageResolverExtensions.g.cs
using Plugin.Maui.SmartNavigation;
using Microsoft.Maui.Hosting;

// ---------------
// <auto-generated>
//   Generated by the SmartNavigation Auto-registration module.
//   https://github.com/matt-goldman/Plugin.Maui.SmartNavigation
// </auto-generated>
// ---------------

namespace TestAssembly;

public static class PageResolverExtensions
{

    public static MauiAppBuilder UseAutodependencies(this MauiAppBuilder builder)
    {
         var ViewModelMappings = new Dictionary<Type, Type>();

         // pages
         builder.Services.AddTransient<global::TestAssembly.HomePage>();


         // ViewModels
         builder.Services.AddTransient<global::TestAssembly.HomePageViewModel>();


         // Services
         builder.Services.AddSingleton<global::TestAssembly.IMyService, global::TestAssembly.MyService>();
         builder.Services.AddSingleton<global::TestAssembly.SingletonService>();
         builder.Services.AddTransient<global::TestAssembly.TransientService>();


         // ViewModel to Page mappings
         ViewModelMappings.Add(typeof(global::TestAssembly.HomePage), typeof(global::TestAssembly.HomePageViewModel));


         // Initialisation
         builder.Services.UseSmartNavigation(ViewModelMappings);
         return builder;
    }
}